// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7bxyREMWLPeVuTqFW3cKyqxsCiUY5fg4',
    appId: '1:585623886506:web:7bbbd94185285643c6ced3',
    messagingSenderId: '585623886506',
    projectId: 'izmirpano-b65ac',
    authDomain: 'izmirpano-b65ac.firebaseapp.com',
    storageBucket: 'izmirpano-b65ac.firebasestorage.app',
    measurementId: 'G-0QKCZ2DLPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCucaZR9c36G4R-PIgZO2g4CdwsRCX3xo',
    appId: '1:585623886506:android:f7636222c308c7fdc6ced3',
    messagingSenderId: '585623886506',
    projectId: 'izmirpano-b65ac',
    storageBucket: 'izmirpano-b65ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeyilB8yCgmuv8vwZLJwnkNMbplNZVYZg',
    appId: '1:585623886506:ios:c69108b07813fbbcc6ced3',
    messagingSenderId: '585623886506',
    projectId: 'izmirpano-b65ac',
    storageBucket: 'izmirpano-b65ac.firebasestorage.app',
    iosBundleId: 'com.example.izpano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeyilB8yCgmuv8vwZLJwnkNMbplNZVYZg',
    appId: '1:585623886506:ios:c69108b07813fbbcc6ced3',
    messagingSenderId: '585623886506',
    projectId: 'izmirpano-b65ac',
    storageBucket: 'izmirpano-b65ac.firebasestorage.app',
    iosBundleId: 'com.example.izpano',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7bxyREMWLPeVuTqFW3cKyqxsCiUY5fg4',
    appId: '1:585623886506:web:3fb4dd449f180079c6ced3',
    messagingSenderId: '585623886506',
    projectId: 'izmirpano-b65ac',
    authDomain: 'izmirpano-b65ac.firebaseapp.com',
    storageBucket: 'izmirpano-b65ac.firebasestorage.app',
    measurementId: 'G-XKCM5E30BT',
  );

}